Project_Work/src/Entity/PatientEntity.php
<?php


namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class PatientEntity
 * @package App\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="patients")
 */
class PatientEntity
{
    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(type="string", length=15, nullable=false, unique=true)
     */
    private $taj;

    /**
     * @var string
     * @ORM\Column(type="string", length=200, nullable=false)
     */
    private $full_name;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @var string
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    private $phone;

    /**
     * @var string
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $known_diseases;

    /**
     * @var string
     * @ORM\Column(type="string", length=200, nullable=false)
     */
    private $address;

    /**
     * @var ArrayCollection|AppointmentEntity
     * @ORM\OneToMany (targetEntity="App\Entity\AppointmentEntity", mappedBy="patient")
     */
    private $appointments;

    /**
     * PatientEntity constructor.
     * @param string $taj
     * @param string $full_name
     * @param int $age
     * @param string $phone
     * @param string $known_diseases
     * @param string $address
     */
    public function __construct(string $taj, string $full_name, int $age, string $phone, string $known_diseases, string $address)
    {
        $this->taj = $taj;
        $this->full_name = $full_name;
        $this->age = $age;
        $this->phone = $phone;
        $this->known_diseases = $known_diseases;
        $this->address = $address;
    }

    /**
     * @return AppointmentEntity|ArrayCollection
     */
    public function getAppointments()
    {
        return $this->appointments;
    }

    /**
     * @param AppointmentEntity|ArrayCollection $appointments
     * @return PatientEntity
     */
    public function setAppointments($appointments)
    {
        $this->appointments = $appointments;
        return $this;
    }

    /**
     * @return string
     */
    public function getTaj(): string
    {
        return $this->taj;
    }

    /**
     * @param string $taj
     * @return PatientEntity
     */
    public function setTaj(string $taj): PatientEntity
    {
        $this->taj = $taj;
        return $this;
    }

    /**
     * @return string
     */
    public function getFullName(): string
    {
        return $this->full_name;
    }

    /**
     * @param string $full_name
     * @return PatientEntity
     */
    public function setFullName(string $full_name): PatientEntity
    {
        $this->full_name = $full_name;
        return $this;
    }

    /**
     * @return int
     */
    public function getAge(): int
    {
        return $this->age;
    }

    /**
     * @param int $age
     * @return PatientEntity
     */
    public function setAge(int $age): PatientEntity
    {
        $this->age = $age;
        return $this;
    }

    /**
     * @return string
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     * @return PatientEntity
     */
    public function setPhone(string $phone): PatientEntity
    {
        $this->phone = $phone;
        return $this;
    }

    /**
     * @return string
     */
    public function getKnownDiseases(): string
    {
        return $this->known_diseases;
    }

    /**
     * @param string $known_diseases
     * @return PatientEntity
     */
    public function setKnownDiseases(string $known_diseases): PatientEntity
    {
        $this->known_diseases = $known_diseases;
        return $this;
    }

    /**
     * @return string
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * @param string $address
     * @return PatientEntity
     */
    public function setAddress(string $address): PatientEntity
    {
        $this->address = $address;
        return $this;
    }
}

Project_Work/src/Controller/NurseController.php
<?php


namespace App\Controller;


use App\Models\AppointmentListModel;
use App\Models\HospitalSelectionModel;
use App\Repository\AppointmentRepository;
use App\Repository\HospitalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NurseController extends AbstractController
{
    private AppointmentRepository $appointmentRepository;
    private HospitalRepository $hospitalRepository;

    /**
     * NurseController constructor.
     * @param AppointmentRepository $appointmentRepository
     * @param HospitalRepository $hospitalRepository
     */
    public function __construct(AppointmentRepository $appointmentRepository, HospitalRepository $hospitalRepository)
    {
        $this->appointmentRepository = $appointmentRepository;
        $this->hospitalRepository = $hospitalRepository;
    }


    /**
     * @param Request $request
     * @return Response
     * @Route("/nurse", name="nurse", methods={"GET", "POST"})
     */
    public function index(Request $request): Response
    {
        $this->denyAccessUnlessGranted("ROLE_NURSE");

        $selectedHospital = intval($request->request->get('hospital_input'));

        $queryParam = $this->getv('hospitalId', 'false');
        if ($queryParam != 'false') {
            $selectedHospital = intval($queryParam);
        }

        list($hospitalList, $appointments) = $this->getTodayView($selectedHospital);

        return $this->render('nurse/nurse.html.twig', ["appointments" => $appointments, "hospitalSelection" => $hospitalList]);
    }

    function getv($key, $default = '', $data_type = '')
    {
        $param = ($_REQUEST[$key] ?? $default);

        if (!is_array($param) && $data_type == 'int') {
            $param = intval($param);
        }

        return $param;
    }

    /**
     * @param int $appointment
     * @return Response
     * @Route("/nurse/appointment/{appointment}/done", name="nurse_vaccination", requirements={"appointment": "\d+"}, methods={"GET"})
     */
    public function vaccineReceived(int $appointment): Response
    {
        $this->denyAccessUnlessGranted("ROLE_NURSE");

        $appointmentEntity = $this->appointmentRepository->findById($appointment);
        if ($appointmentEntity) {
            $appointmentEntity->setReceived(true);
            $this->appointmentRepository->updateEntity($appointmentEntity);
        }

        return $this->redirectToRoute('nurse', ['hospitalId' => $appointmentEntity->getHospital()->getHospitalId()]);
    }

    /**
     * @param int $selectedHospital
     * @return array[]
     */
    private function getTodayView(int $selectedHospital): array
    {
        $appointments = array();
        $hospitalList = array();

        $hospitals = $this->hospitalRepository->list();

        if (!$selectedHospital && count($hospitals) > 0) {
            $selectedHospital = $hospitals[0]->getHospitalId();
        }

        $filteredAppointments = $this->appointmentRepository->listByBookedDateAndHospital(new \DateTime('now'), $selectedHospital);
        foreach ($hospitals as $hospital) {
            array_push($hospitalList, new HospitalSelectionModel($hospital->getHospitalId(), $hospital->getName(), $hospital->getHospitalId() == $selectedHospital));
        }
        foreach ($filteredAppointments as $appointment) {
            $diseases = $appointment->getPatient()->getKnownDiseases();
            array_push($appointments, new AppointmentListModel($appointment->getAppointmentId(), $appointment->getPatient()->getFullName(), $appointment->getPatient()->getTaj(), $appointment->getPatient()->getAge(), $appointment->getPatient()->getAddress(), $diseases ? $diseases : "none", $appointment->getVaccine()->getName(), $appointment->isReceived()));
        }
        return array($hospitalList, $appointments);
    }
}

Project_Work/templates/nurse/nurse.html.twig
{# @var appointments \App\Models\AppointmentListModel[] #}
{# @var hospitalSelection \App\Models\HospitalSelectionModel[] #}
{% set patientRowClass = "grid grid-cols-9 text-center border-b border-gray-400" %}

{% extends 'base.html.twig' %}

{% block title 'Nurse' %}

{% block body %}
    <div class="w-full min-h-full nurse-bg flex font-sans items-center justify-center">
        <div class="w-3/4 h-full bg-white border shadow-md rounded-2xl p-6 mt-24 mb-24 flex flex-col flex-none justify-between space-y-3">
            <h1 class="text-2xl font-medium inline-block">Patients</h1>
            <div>
                <form method="post" action="{{ path('nurse') }}">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="hospital_input">Please select a
                        hospital</label>
                    <div class="flex w-full">
                        <div class="relative w-full">
                            <select class="block appearance-none w-full bg-white shadow border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                                    id="hospital_input" name="hospital_input" onchange="this.form.submit()">
                                {% for hospital in hospitalSelection %}
                                    {% if hospital.selected %}
                                        <option value="{{ hospital.id }}" selected>{{ hospital.name }}</option>
                                    {% else %}
                                        <option value="{{ hospital.id }}">{{ hospital.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 20 20">
                                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                                </svg>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="border w-full h-full flex flex-col">
                <div class="grid grid-cols-9 text-center bg-gray-200">
                    <h1 class="border-r border-gray-400 col-span-2">Name</h1>
                    <h1 class="border-r border-gray-400">TAJ</h1>
                    <h1 class="border-r border-gray-400">Age</h1>
                    <h1 class="border-r border-gray-400">Address</h1>
                    <h1 class="border-r border-gray-400 col-span-2">Known diseases</h1>
                    <h1 class="border-r border-gray-400">Vaccine</h1>
                    <h1>Received</h1>
                </div>
                <div>
                    {% for appointment in appointments %}
                        <div class="{{ appointment.received? patientRowClass ~ " bg-green-200" : patientRowClass }}">
                            <h1 class="border-r border-gray-400 col-span-2 truncate">{{ appointment.name }}</h1>
                            <h1 class="border-r border-gray-400">{{ appointment.taj }}</h1>
                            <h1 class="border-r border-gray-400">{{ appointment.age }}</h1>
                            <div class="tooltip">
                                <h1 class="border-r border-gray-400 truncate">{{ appointment.address }}</h1>
                                <span class="tooltiptext">{{ appointment.address }}</span>
                            </div>
                            <div class="tooltip col-span-2">
                                <h1 class="border-r border-gray-400 truncate">{{ appointment.knownDiseases }}</h1>
                                <span class="tooltiptext">{{ appointment.knownDiseases }}</span>
                            </div>
                            <h1 class="border-r border-gray-400">{{ appointment.vaccine }}</h1>
                            <div class="flex items-center justify-center">
                                <a href="{{ path('nurse_vaccination',{'appointment':  appointment.id}) }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-600" fill="none"
                                         viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}